-- Deprecated migration intentionally left as no-op.
-- Destructive data cleanup moved to manual script:
--   supabase/scripts/clear_payment_data.sql
-- This prevents automatic truncation during migration runs.
